"""File→env→default configuration resolution for CLIO Agent.

A single, dependency-free resolver so configuration is *sharable* (committable
to a YAML file) instead of scattered across hardcoded constants and bare
``os.environ`` reads. Every knob resolves with one precedence:

1. **config FILE** — workspace ``<cwd>/.clio/config.yaml`` deep-merged OVER
   user ``<config>/clio-agent/config.yaml`` (mirrors the ``mcp.yaml`` discovery
   in :mod:`clio_agent.tools.mcp_config`; honours ``XDG_CONFIG_HOME``).
2. **environment** — ``os.environ`` (already seeded by ``.env`` via
   :func:`clio_agent.config.load_project_env_file`, so dotenv keeps working).
3. **committed defaults** — the packaged ``config.defaults.yaml`` base layer (a
   flat dotted-key document generated by ``scripts/gen_env_reference.py``,
   shipped inside the wheel next to this module). It enumerates every knob's
   in-code default so the runtime can read the same values it documents.
4. **default** — the in-code ``default=`` fallback (the *operative* one).

The FILE wins over the environment on purpose: the file is the sharable source
of truth and the environment is the fallback used only when a key is absent from
the file. This is the inverse of the 12-factor "env overrides file" convention,
and is a deliberate project decision (see the logging/config plan).

Because the file layer is authoritative, the test suite varies configuration
through a per-test ``config.yaml`` (written under a tmp ``XDG_CONFIG_HOME``), not
through ambient process env — the autouse ``allow_pytest_tmp_path`` fixture writes
the test-default knobs there, and ``tests._config_layer`` mutates them per test
(#985: the conftest "env soup" was dissolved to config-first, since a ``setenv``
on a file-backed knob would be shadowed by that file).

The committed-defaults layer sits BELOW the environment (env still overrides it)
and ABOVE the in-code default. Because ``config.defaults.yaml`` is generated
from — and drift-tested against — the very same in-code ``default=`` arguments
(``tests/test_docs/test_env_reference.py``), layers 3 and 4 return identical
values, so introducing the base layer changes no observable behaviour: it is a
readable, committed mirror of the in-code defaults, not a new source of truth.
The in-code ``default=`` remains operative — if the packaged file is missing or
corrupt, the layer degrades to ``{}`` with a structured warning (no silent
fallback) and resolution proceeds straight to the in-code default.

**Deliberately NOT resolved through this store** (they stay bare ``os.environ``
reads on purpose, so a config file cannot silently redirect them):

- *Bootstrap tier* — read before this store (or its file discovery) exists, so a
  ``resolve`` call here would recurse or read a not-yet-loaded layer:
  ``CLIO_USER_DIR`` (``clio_agent.paths``; :meth:`ConfigStore._load` imports
  ``paths``), ``CLIO_ENV_FILE`` / ``CLIO_ENV_FILE_LOADED`` (the dotenv loader in
  ``clio_agent.config``), and ``XDG_CONFIG_HOME`` (drives the file discovery).
- *Secret tier* — never committed to a shared config file; env-only by policy:
  ``CLIO_LM_API_KEY``, ``CLIO_ARGONNE_TOKEN``, ``ALCF_INFERENCE_TOKEN``, and the
  ``CLIO_CRED_*`` credential vars.
- *Provider auth-status probes* — presence-of-env checks that drive the auth UI
  in ``clio_agent.gact.routes.providers`` must reflect the real process env, not
  a file layer, so they stay env-direct.

Usage::

    from clio_agent import conf
    timeout = conf.resolve("limits.lm_call_s", env="CLIO_MAX_LM_CALL_S",
                           default=1800.0, cast=conf.as_float)
    level = conf.resolve("debug.level", env="CLIO_DEBUG", default="low")
"""

from __future__ import annotations

import logging
import os
import threading
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Any, TypeVar

import yaml

T = TypeVar("T")

logger = logging.getLogger(__name__)

_USER_CONFIG_RELPATH = ("clio-agent", "config.yaml")
_WORKSPACE_CONFIG_RELPATH = (".clio", "config.yaml")

# The committed base-layer defaults document, shipped inside the wheel next to
# this module (``src/clio_agent/config.defaults.yaml``). Generated + drift-tested
# by ``scripts/gen_env_reference.py``; a flat dotted-key → default mapping.
_DEFAULTS_FILENAME = "config.defaults.yaml"

# Sentinel distinguishing "key absent from file" from "file value is None/empty".
_UNSET: Any = object()

# Public alias so callers can test a :meth:`ConfigStore.file_value` result for
# "key absent from the file layer" (used to label config-vs-env provenance).
UNSET: Any = _UNSET


# --------------------------------------------------------------------------- #
# Cast helpers — accept the raw value from any source (already-typed YAML scalar
# or a string from the environment) and coerce explicitly. Raise on garbage so a
# misconfigured value fails loudly rather than silently falling back.
# --------------------------------------------------------------------------- #

_TRUE_TOKENS = {"1", "true", "yes", "on", "y", "t"}
_FALSE_TOKENS = {"0", "false", "no", "off", "n", "f", ""}


def as_str(value: Any) -> str:
    """Coerce to ``str`` (pass through actual strings unchanged)."""
    return value if isinstance(value, str) else str(value)


def as_bool(value: Any) -> bool:
    """Coerce a YAML bool/number or an env string to ``bool``.

    Accepts ``1/true/yes/on/y/t`` (true) and ``0/false/no/off/n/f``/empty
    (false), case-insensitively. Raises ``ValueError`` on anything else.
    """
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    token = str(value).strip().lower()
    if token in _TRUE_TOKENS:
        return True
    if token in _FALSE_TOKENS:
        return False
    raise ValueError(f"cannot interpret {value!r} as a boolean")


def as_int(value: Any) -> int:
    """Coerce to ``int``. Raises ``ValueError``/``TypeError`` on non-integers."""
    if isinstance(value, bool):
        raise ValueError(f"refusing to read boolean {value!r} as an int")
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    return int(str(value).strip())


def as_float(value: Any) -> float:
    """Coerce to ``float``. Raises ``ValueError``/``TypeError`` on non-numbers."""
    if isinstance(value, bool):
        raise ValueError(f"refusing to read boolean {value!r} as a float")
    if isinstance(value, (int, float)):
        return float(value)
    return float(str(value).strip())


def as_csv(value: Any) -> list[str]:
    """Coerce a YAML list or a comma-separated string to ``list[str]``.

    Whitespace-trimmed; empty items are dropped.
    """
    if isinstance(value, (list, tuple)):
        return [str(item).strip() for item in value if str(item).strip()]
    return [part.strip() for part in str(value).split(",") if part.strip()]


# --------------------------------------------------------------------------- #
# File discovery + merge
# --------------------------------------------------------------------------- #


def _read_yaml_mapping(path: Path) -> dict[str, Any]:
    """Read a YAML file into a dict, returning ``{}`` on missing/invalid input."""
    if not path.is_file():
        return {}
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError):
        return {}
    return dict(data) if isinstance(data, Mapping) else {}


def _deep_merge(base: Mapping[str, Any], override: Mapping[str, Any]) -> dict[str, Any]:
    """Recursively merge ``override`` onto ``base`` (override wins per leaf)."""
    out: dict[str, Any] = dict(base)
    for key, value in override.items():
        existing = out.get(key)
        if isinstance(value, Mapping) and isinstance(existing, Mapping):
            out[key] = _deep_merge(existing, value)
        else:
            out[key] = value
    return out


# Snapshot at IMPORT time: on Python 3.12 ``Path()`` selects WindowsPath vs
# PosixPath by ``os.name`` AT CALL TIME, and this path is reached from the LAZY
# defaults load, which can run inside a test's ``os.name`` monkeypatch window.
_PACKAGED_DEFAULTS_PATH: Path = Path(__file__).with_name(_DEFAULTS_FILENAME)


def _packaged_defaults_path() -> Path:
    """Return the path to the wheel-shipped ``config.defaults.yaml``."""
    return _PACKAGED_DEFAULTS_PATH


def _read_flat_defaults(path: Path) -> dict[str, Any]:
    """Read the flat dotted-key committed-defaults document.

    Returns ``{dotted_key: default}``. A missing or corrupt file degrades to an
    empty mapping and emits a structured warning (no silent fallback): resolution
    then proceeds straight to the operative in-code ``default=`` for every knob.
    The document is intentionally *flat* (top-level ``"arc.store": "cte"`` keys),
    matched by exact dotted key — not the nested shape ``config.yaml`` uses.
    """
    if not path.is_file():
        logger.warning(
            "config_defaults_layer_unavailable reason=missing_packaged_file path=%s; "
            "resolving from in-code defaults",
            path,
        )
        return {}
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as exc:
        logger.warning(
            "config_defaults_layer_unavailable reason=corrupt_packaged_file path=%s error=%r; "
            "resolving from in-code defaults",
            path,
            exc,
        )
        return {}
    if not isinstance(data, Mapping):
        logger.warning(
            "config_defaults_layer_unavailable reason=non_mapping_packaged_file path=%s; "
            "resolving from in-code defaults",
            path,
        )
        return {}
    return {str(key): value for key, value in data.items()}


class ConfigStore:
    """Lazily-loaded, cached merge of the user + workspace config files.

    The file layer is loaded once and cached; :meth:`reload` clears the cache.
    The environment layer is read live on every :meth:`resolve` call, so env
    changes take effect without a reload (matching how ``os.environ`` is used
    everywhere else).
    """

    def __init__(
        self,
        *,
        home: Path | None = None,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
        defaults_path: Path | None = None,
    ) -> None:
        self._home = home
        self._cwd = cwd
        self._env = env
        # The committed base-layer defaults document (``None`` -> the packaged
        # wheel copy). Tests inject a path to exercise the missing/corrupt
        # degraded path without disturbing the packaged file.
        self._defaults_path = defaults_path
        self._lock = threading.Lock()
        self._data: dict[str, Any] | None = None
        self._defaults: dict[str, Any] | None = None
        # Path-class selection is os.name-dynamic on 3.12 — snapshot outside
        # any monkeypatch window (see _load).
        self._cwd_snapshot: Path = Path.cwd()
        # Same os.name-dynamic hazard as cwd: snapshot home outside any
        # monkeypatch window; None = no resolvable home (scrubbed envs).
        try:
            self._home_snapshot: Path | None = Path.home()
        except RuntimeError:
            self._home_snapshot = None
        self._user_dir_snapshot: Path | None = self._compute_user_dir()

    def _env_map(self) -> Mapping[str, str]:
        return self._env if self._env is not None else os.environ

    def _compute_user_dir(self) -> Path | None:
        """Resolve the per-user config dir NOW (construction/reload time).

        ``paths.user_config_dir_for`` constructs ``Path`` objects, whose class is
        selected by ``os.name`` at call time on Python 3.12 — so this must never
        run inside the lazy ``_load`` (a test's os.name monkeypatch window).
        ``None`` = no resolvable home (scrubbed envs); the user layer is skipped
        with a logged reason at load.
        """
        from clio_agent import paths  # noqa: PLC0415 - avoid import cycle at module load

        home = self._home or self._home_snapshot
        if home is None:
            return None
        try:
            return paths.user_config_dir_for(home, self._env_map())
        except RuntimeError:
            return None

    def _load(self) -> dict[str, Any]:
        # The cwd snapshot is taken at reload()/construction time, NEVER here:
        # this lazy load can run inside a test's os.name monkeypatch window, and
        # Python 3.12's Path() selects WindowsPath/PosixPath by os.name AT CALL
        # TIME — Path.cwd() under a patched os.name raises NotImplementedError
        # on the other OS. reload() and __init__ always run unpatched.
        cwd = self._cwd or self._cwd_snapshot
        user: dict[str, Any] = {}
        try:
            user_dir = self._user_dir_snapshot
            if user_dir is None:
                raise RuntimeError("no home directory was resolvable at store construction")
        except RuntimeError as exc:
            # No resolvable home directory — e.g. on Windows, ``Path.home()``
            # raises when USERPROFILE/HOME are absent from the environment
            # (scrubbed test envs, hardened services). The per-user config
            # layer is then explicitly absent: emit the reason (no silent
            # fallback) and resolve from workspace file → env → default.
            logger.debug("user config layer skipped: no home directory resolvable (%s)", exc)
        else:
            user = _read_yaml_mapping(user_dir / _USER_CONFIG_RELPATH[-1])
        workspace = _read_yaml_mapping(cwd.joinpath(*_WORKSPACE_CONFIG_RELPATH))
        return _deep_merge(user, workspace)

    @property
    def data(self) -> dict[str, Any]:
        """The merged file config (workspace over user), loaded once and cached."""
        with self._lock:
            if self._data is None:
                self._data = self._load()
            return self._data

    @property
    def defaults(self) -> dict[str, Any]:
        """The committed base-layer defaults (flat dotted keys), loaded + cached."""
        with self._lock:
            if self._defaults is None:
                self._defaults = _read_flat_defaults(
                    self._defaults_path or _packaged_defaults_path()
                )
            return self._defaults

    def reload(self) -> None:
        """Drop the cached file + defaults config so the next access re-reads from disk."""
        with self._lock:
            self._data = None
            self._defaults = None
            # Re-snapshot the workspace root + home: reload() runs unpatched
            # (e.g. the per-test fixture after monkeypatch.chdir), unlike the
            # lazy _load.
            self._cwd_snapshot = Path.cwd()
            try:
                self._home_snapshot = Path.home()
            except RuntimeError:
                self._home_snapshot = None
            self._user_dir_snapshot = self._compute_user_dir()

    def file_value(self, key: str) -> Any:
        """Return the dotted-path value from the file layer, or ``_UNSET``."""
        node: Any = self.data
        for part in key.split("."):
            if isinstance(node, Mapping) and part in node:
                node = node[part]
            else:
                return _UNSET
        return node

    def resolve(
        self,
        key: str,
        *,
        env: str,
        default: T,
        cast: Callable[[Any], T] | None = None,
    ) -> T:
        """Resolve ``key`` by file → env → committed-default → in-code precedence.

        Args:
            key: dotted path into the YAML file (e.g. ``"debug.level"``).
            env: environment variable name checked when the file lacks ``key``.
            default: the operative in-code fallback, returned when no file, env
                or committed-default layer provides a value.
            cast: optional coercion applied to a file/env/committed-default value
                (not to ``default``). Use the module ``as_*`` helpers. When
                ``None`` the value is returned unchanged (env values are
                therefore strings).

        Returns:
            The resolved, optionally-cast value.
        """
        file_value = self.file_value(key)
        if file_value is not _UNSET:
            return cast(file_value) if cast is not None else file_value
        env_value = self._env_map().get(env)
        if env_value is not None and env_value.strip() != "":
            return cast(env_value) if cast is not None else env_value  # type: ignore[return-value]
        # Committed base-layer defaults (below env, above the in-code default).
        # Flat dotted-key lookup; a present key mirrors the in-code default, so a
        # hit here returns the same value the ``return default`` below would.
        default_value = self.defaults.get(key, _UNSET)
        if default_value is not _UNSET:
            return cast(default_value) if cast is not None else default_value
        return default


# Process-wide default store (real home/cwd/env). Tests construct their own
# ``ConfigStore`` with injected paths; production code uses these module funcs.
_STORE = ConfigStore()


def resolve(
    key: str,
    *,
    env: str,
    default: T,
    cast: Callable[[Any], T] | None = None,
) -> T:
    """Resolve a config value via the process-wide store (file → env → default)."""
    return _STORE.resolve(key, env=env, default=default, cast=cast)


def reload() -> None:
    """Clear the process-wide store's cached file config."""
    _STORE.reload()


def store() -> ConfigStore:
    """Return the process-wide :class:`ConfigStore` (for tests / introspection)."""
    return _STORE
