"""Tests for scripts/check_bundle_matches_lock.py and the bundle install-set contract.

The bundled CLIO Desktop runtime must install exactly the ``uv.lock`` set:
one extras list (``BUNDLE_EXTRAS``) shared by the lock export and the install
in both build scripts, no package pinned outside the lock, and a check that
fails on version drift AND on packages the lock export does not cover.
"""

from __future__ import annotations

import importlib.util
import re
import sys
import tomllib
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "check_bundle_matches_lock.py"
PS1 = REPO_ROOT / "install" / "build-gact-runtime.ps1"
SH = REPO_ROOT / "install" / "build-gact-runtime.sh"


def _load_module() -> ModuleType:
    """Import the script as a module (scripts/ is not a package)."""
    spec = importlib.util.spec_from_file_location("check_bundle_matches_lock", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


cbl = _load_module()


def _code_lines(path: Path) -> list[str]:
    """Return a script's non-comment lines."""
    return [
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if not line.lstrip().startswith("#")
    ]


def test_build_scripts_share_the_checks_bundle_extras() -> None:
    """Both builders define BUNDLE_EXTRAS once, identical to the check's constant."""
    ps1 = PS1.read_text(encoding="utf-8")
    sh = SH.read_text(encoding="utf-8")
    ps1_defs = re.findall(r"^\$BundleExtras = @\((.*)\)$", ps1, flags=re.MULTILINE)
    sh_defs = re.findall(r'^BUNDLE_EXTRAS="(.*)"$', sh, flags=re.MULTILINE)
    assert len(ps1_defs) == 1 and len(sh_defs) == 1
    ps1_extras = tuple(item.strip().strip("'") for item in ps1_defs[0].split(","))
    sh_extras = tuple(sh_defs[0].split())
    assert ps1_extras == cbl.BUNDLE_EXTRAS
    assert sh_extras == cbl.BUNDLE_EXTRAS


def test_build_scripts_export_and_install_from_the_same_list() -> None:
    """The export and the install both read the list; no argonne-only export remains."""
    ps1 = PS1.read_text(encoding="utf-8")
    sh = SH.read_text(encoding="utf-8")
    assert "foreach ($extra in $BundleExtras) { $exportArgs += @('--extra', $extra) }" in ps1
    assert "$bundleSpec = \"$spec[$($BundleExtras -join ',')]\"" in ps1
    assert "for extra in $BUNDLE_EXTRAS; do EXPORT_EXTRA_ARGS=" in sh
    assert "BUNDLE_SPEC=\"${SPEC}[$(echo \"$BUNDLE_EXTRAS\" | tr ' ' ',')]\"" in sh
    for script in (ps1, sh):
        assert "'--extra', 'argonne'" not in script
        assert "--extra argonne" not in script


@pytest.mark.parametrize("path", [PS1, SH], ids=["ps1", "sh"])
def test_build_scripts_pin_nothing_outside_the_lock(path: Path) -> None:
    """No requirement pin (``name==version``) or global prerelease flag in code lines."""
    pin = re.compile(r"""['"][A-Za-z0-9_.\-\[\]]+(==|>=|~=)[0-9]""")
    offenders = [line for line in _code_lines(path) if pin.search(line)]
    assert offenders == []
    assert not any("--prerelease" in line for line in _code_lines(path))


def test_bundle_extras_exist_and_desktop_carries_clio_kit() -> None:
    """Every bundle extra is declared; clio-kit is locked through the desktop extra."""
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    extras = pyproject["project"]["optional-dependencies"]
    for extra in cbl.BUNDLE_EXTRAS:
        assert extra in extras, extra
    desktop = extras["desktop"]
    clio_kit = [req for req in desktop if req.startswith("clio-kit")]
    assert len(clio_kit) == 1
    locked = cbl.load_lock_versions(REPO_ROOT / "uv.lock")
    assert clio_kit[0] == f"clio-kit=={locked['clio-kit']}"


def test_real_lock_export_covers_the_bundle_packages() -> None:
    """The real export for BUNDLE_EXTRAS includes what the bundle ships.

    clio-kit and the Web Search adapter's deps come from the desktop extra;
    pytz is pulled in by those deps (the package that drifted unlocked).
    """
    scope = cbl.load_bundle_scope(REPO_ROOT, cbl.BUNDLE_EXTRAS)
    for name in ("clio-kit", "click", "iowarp-core", "globus-sdk", "trafilatura", "ddgs", "pytz"):
        assert name in scope, name
    assert "clio-agent" not in scope  # --no-emit-project


def test_parse_export_names_handles_pins_urls_markers_and_annotations() -> None:
    """Registry pins, direct URLs, markers, extras and comments parse to bare names."""
    text = (
        "# This file was autogenerated by uv\n"
        "-e .\n"
        "Click==8.3.3\n"
        "    # via clio-kit\n"
        "colorama==0.4.6 ; sys_platform == 'win32'\n"
        "clio-schemas @ git+https://github.com/iowarp/clio-schemas.git@d68c72c\n"
        "fastmcp-slim[client,server]==4.0.0b5\n"
        "Iowarp_Core==2.2.1\n"
        "\n"
    )
    assert cbl.parse_export_names(text) == {
        "click",
        "colorama",
        "clio-schemas",
        "fastmcp-slim",
        "iowarp-core",
    }


def test_find_drift_flags_mismatch_and_unlocked_but_skips_local_projects() -> None:
    """A mismatch and an out-of-export package fail; local/interpreter-seeded ones do not."""
    locked = {"click": "8.3.3", "pytz": "2026.3.post1", "iowarp-core": "2.2.1"}
    scope = {"click", "iowarp-core"}  # pytz is in the lock but NOT in this export
    installed = {
        "click": "8.3.3",
        "iowarp-core": "2.1.0",
        "pytz": "2026.4",
        "surprise": "1.0",
        "clio-agent": "0.9.4.17",
        "web-mcp": "2.1.0",
        "pip": "26.1.2",
    }
    assert cbl.find_drift(locked, installed, scope) == [
        ("iowarp-core", "2.2.1", "2.1.0"),
        ("pytz", None, "2026.4"),
        ("surprise", None, "1.0"),
    ]


def test_find_drift_is_empty_for_an_exact_install() -> None:
    """An install equal to the locked export reports no drift."""
    locked = {"click": "8.3.3", "clio-kit": "2.10.6"}
    assert cbl.find_drift(locked, dict(locked), set(locked)) == []


def test_verify_runtime_reports_named_packages_and_fails_on_drift(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str], tmp_path: Path
) -> None:
    """The verifier prints the named packages and a drift table, exiting 1."""
    monkeypatch.setattr(cbl, "load_lock_versions", lambda _lock: {"click": "8.3.3"})
    monkeypatch.setattr(cbl, "load_bundle_scope", lambda _p, _e: {"click"})
    monkeypatch.setattr(
        cbl, "load_installed_versions", lambda _py: {"click": "8.5.0", "pytz": "2026.4"}
    )
    code = cbl.verify_runtime(tmp_path / "python", tmp_path / "uv.lock", tmp_path)
    out = capsys.readouterr()
    assert code == 1
    assert "click: locked='8.3.3' installed='8.5.0'" in out.out
    assert "click: locked=8.3.3 installed=8.5.0" in out.err
    assert "pytz: NOT in the lock export, installed=2026.4" in out.err


def test_verify_runtime_passes_on_exact_install(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str], tmp_path: Path
) -> None:
    """Zero drift exits 0 with an OK line."""
    versions = {"click": "8.3.3", "clio-kit": "2.10.6", "iowarp-core": "2.2.1"}
    monkeypatch.setattr(cbl, "load_lock_versions", lambda _lock: versions)
    monkeypatch.setattr(cbl, "load_bundle_scope", lambda _p, _e: set(versions))
    monkeypatch.setattr(cbl, "load_installed_versions", lambda _py: dict(versions))
    assert cbl.verify_runtime(tmp_path / "python", tmp_path / "uv.lock", tmp_path) == 0
    assert "OK: all 3 lock-resolved packages" in capsys.readouterr().out


def test_run_uv_raises_with_stderr_on_failure() -> None:
    """A failing uv call surfaces as RuntimeError carrying uv's own message."""
    with pytest.raises(RuntimeError, match="failed"):
        cbl._run_uv(["pip", "compile", "--definitely-not-a-flag"])


def test_main_rejects_a_missing_lock(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A missing lock file is a loud exit 1, not a vacuous pass."""
    monkeypatch.setattr(
        sys, "argv", ["check", "--resolve", "--lock", str(tmp_path / "missing.lock")]
    )
    assert cbl.main() == 1
    assert "lock not found" in capsys.readouterr().err


def test_ci_resolves_the_bundle_install_set_on_every_pr() -> None:
    """The regular CI workflow (PR + push) runs the resolve check."""
    ci = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "pull_request:" in ci
    assert "python scripts/check_bundle_matches_lock.py --resolve" in ci
