"""An installed Agent Blueprint pack's files: copy, checksum, install metadata.

Owner module for the filesystem work of putting a pack on disk (split out of
``gact/agent_blueprints.py``, file-size ratchet #774). Every call here uses the
extended-length helpers in :mod:`clio_agent.platform_paths`: a pack copied under a
long user dir (a long user name, a packaged app's ``LocalCache`` redirection) or
staged beside a random suffix by the default-registry sync crosses Windows' 260
character limit deep in the tree, where an ordinary path raises ``[WinError 206]
The filename or extension is too long``.
"""

from __future__ import annotations

import hashlib
import shutil
from pathlib import Path
from typing import Any

from clio_agent.platform_paths import tree_files, win_extended_path

#: The install metadata file at a pack's root (excluded from the pack checksum).
INSTALL_METADATA_NAME = ".clio-install.md"
RUNTIME_DIRECTORIES = frozenset(
    {".git", ".venv", "node_modules", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
)


def blueprint_files(root: Path) -> list[tuple[Path, str]]:
    """Enumerate pack source, excluding machine-local runtimes and generated bytecode."""
    return [
        (relative, filename)
        for relative, filename in tree_files(root, excluded_dirs=RUNTIME_DIRECTORIES)
        if relative.suffix not in {".pyc", ".pyo"}
        and relative.name not in RUNTIME_DIRECTORIES | {".DS_Store"}
    ]


def copy_blueprint_tree(source: Path, destination: Path) -> None:
    """Copy portable blueprint source; installed dependencies belong to the target runtime."""
    shutil.copytree(
        win_extended_path(source.resolve()),
        win_extended_path(destination.resolve()),
        ignore=shutil.ignore_patterns(*RUNTIME_DIRECTORIES, "*.pyc", "*.pyo", ".DS_Store"),
    )


def write_install_metadata(root: Path, metadata: dict[str, Any]) -> None:
    """Write ``metadata`` as ``key: value`` lines to the pack's install metadata file."""
    lines = ["# CLIO Agent Blueprint install metadata", ""]
    for key, value in metadata.items():
        lines.append(f"{key}: {value}")
    with open(win_extended_path(root / INSTALL_METADATA_NAME), "w", encoding="utf-8") as out:
        out.write("\n".join(lines).strip() + "\n")


def tree_checksum(root: Path) -> str:
    """SHA-256 over portable source paths and bytes, in sorted order.

    Install metadata and local runtimes/caches are excluded. Portable source uses
    the same relative-path ordering as older checksums. A legacy snapshot that
    accidentally bundled a runtime is treated conservatively as changed.
    """
    digest = hashlib.sha256()
    for relative, os_path in blueprint_files(root):
        if relative.name == INSTALL_METADATA_NAME:
            continue
        digest.update(str(relative).encode())
        with open(os_path, "rb") as handle:
            while block := handle.read(1024 * 1024):
                digest.update(block)
    return digest.hexdigest()


def read_install_metadata(root: Path) -> dict[str, str]:
    """Read the installed snapshot's source identity and revision receipt."""
    path = root / ".clio-install.md"
    if not path.exists():
        return {}
    rows: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw or raw.startswith("#") or ":" not in raw:
            continue
        key, _, value = raw.partition(":")
        rows[key.strip()] = value.strip()
    return rows
